timeout: no
default_entry: 1
graphics: yes
wallpaper: boot():/boot/limine/limine-background.jpg
wallpaper_style: stretched

/oxideOS
    protocol: multiboot1
    kernel_path: boot():/boot/oxideOS.bin
    kernel_cmdline: oxideOS bootloader=limine
